// Package liveeval executes trusted, local synthetic fixtures through a real
// Aegis review binary. It never consumes the golden replay report corpus.
package liveeval

import (
	"time"

	"github.com/Molly166/AegisCodeAgent/internal/githubreport"
	"github.com/Molly166/AegisCodeAgent/internal/review"
)

const SchemaVersion = "live-v1"

type Corpus struct {
	SchemaVersion string `json:"schema_version"`
	Description   string `json:"description"`
	Cases         []Case `json:"cases"`
}

// Source files are literal UTF-8 contents, not shell commands or remote URLs.
// Head overlays Base. go.mod is generated by the harness, with no dependencies.
type Case struct {
	ID           string            `json:"id"`
	Title        string            `json:"title"`
	Description  string            `json:"description"`
	Kind         string            `json:"kind"`
	Base         map[string]string `json:"base"`
	Head         map[string]string `json:"head"`
	ExpectedGate string            `json:"expected_gate"`
	Expected     []ExpectedFinding `json:"expected_findings"`
}

type ExpectedFinding struct {
	ID        string                `json:"id"`
	Priority  githubreport.Priority `json:"priority"`
	Category  review.Category       `json:"category"`
	Path      string                `json:"path"`
	StartLine int                   `json:"start_line"`
	EndLine   int                   `json:"end_line"`
	// At least one semantic phrase must appear in title, description or evidence.
	// This is a conservative lexical rubric, not a semantic correctness judge.
	EvidenceTermsAny []string `json:"evidence_terms_any"`
}

type Config struct {
	Corpus              string
	Binary              string
	GoBinary            string
	Repeats             int
	CaseTimeout         time.Duration
	Provider            string
	Model               string
	APIKeyEnv           string
	BaseURL             string
	AllowCustomEndpoint bool
	DisableVerifier     bool
	Analyzers           string
	Gate                githubreport.Options
}

type RunResult struct {
	CaseID         string             `json:"case_id"`
	Title          string             `json:"title"`
	Kind           string             `json:"kind"`
	Repeat         int                `json:"repeat"`
	BaseCommit     string             `json:"base_commit,omitempty"`
	HeadCommit     string             `json:"head_commit,omitempty"`
	ExpectedGate   string             `json:"expected_gate"`
	ActualGate     string             `json:"actual_gate"`
	Passed         bool               `json:"passed"`
	Incomplete     bool               `json:"incomplete"`
	Error          string             `json:"error,omitempty"`
	DurationMillis int64              `json:"duration_ms"`
	Tokens         int                `json:"tokens"`
	AgentCompleted bool               `json:"agent_completed"`
	AgentStatus    review.AgentStatus `json:"agent_status,omitempty"`
	NeedsReview    int                `json:"needs_review"`
	Expected       []ExpectedFinding  `json:"expected_findings"`
	MatchedIDs     []string           `json:"matched_ids"`
	MissedIDs      []string           `json:"missed_ids"`
	Unexpected     []review.Finding   `json:"unexpected_findings"`
	// Fresh reports are embedded so temporary checkouts can be removed while
	// retaining the exact commits, evidence, model usage, and stage statuses.
	Review *review.ReviewReport `json:"review,omitempty"`
}

type Rate struct {
	Numerator   int      `json:"numerator"`
	Denominator int      `json:"denominator"`
	Value       *float64 `json:"value"`
}

type Metrics struct {
	UniqueCases         int             `json:"unique_cases"`
	Runs                int             `json:"runs"`
	PassedRuns          int             `json:"passed_runs"`
	Precision           Rate            `json:"finding_precision"`
	Recall              Rate            `json:"finding_recall"`
	PriorityRecall      map[string]Rate `json:"priority_recall"`
	GateAccuracy        Rate            `json:"gate_accuracy"`
	FalseBlockRate      Rate            `json:"clean_false_block_rate"`
	IncompleteRate      Rate            `json:"incomplete_rate"`
	AgentCompletionRate Rate            `json:"agent_completion_rate"`
	GateConsistency     Rate            `json:"gate_consistency"`
	Tokens              int             `json:"tokens"`
	MeanDurationMillis  float64         `json:"mean_duration_ms"`
	P95DurationMillis   int64           `json:"p95_duration_ms"`
}

type Report struct {
	SchemaVersion   string               `json:"schema_version"`
	Mode            string               `json:"mode"`
	GeneratedAt     time.Time            `json:"generated_at"`
	CorpusSHA256    string               `json:"corpus_sha256"`
	BinarySHA256    string               `json:"binary_sha256"`
	GoToolchain     string               `json:"go_toolchain"`
	GoBinary        string               `json:"go_binary"`
	Provider        string               `json:"provider"`
	RequestedModel  string               `json:"requested_model,omitempty"`
	LiveModel       bool                 `json:"live_model_requested"`
	Repeats         int                  `json:"repeats"`
	Analyzers       string               `json:"analyzers"`
	VerifierEnabled bool                 `json:"verifier_enabled"`
	Gate            githubreport.Options `json:"gate"`
	Limitations     []string             `json:"limitations"`
	Metrics         Metrics              `json:"metrics"`
	Runs            []RunResult          `json:"runs"`
}
